project_id: "YOUR_PROJECT_ID"
api_token_env: "CROWDIN_PERSONAL_TOKEN"
base_path: "."
base_url: "https://api.crowdin.com"

files:
  - source: "/locale/en-us.json"
    translation: "/locale/%locale%.json"
