# This is a configuration file for Weblate.
# It is used to define the project and component.

# The project slug.
project: zahid-s-portfolio
# The component slug.
component: website
# The file format to use.
file_format: json
# The path to the source language file.
source_language: en-us
# The path to the translation files.
translation_files: "locale/*.json"
# The path to the template file.
template: "locale/en-us.json"
# The file mask to use for new translations.
new_base: "locale/en-us.json"
# The file mask for new translations.
filemask: "locale/*.json"
# The language code style to use.
langcode_style: bcp
# The merge style to use.
merge_style: "merge"
